### ISSUE TITLE
img4.c:14:10: fatal error: 'openssl/bn.h' file not found

### ISSUE THREAD

**Issue by icylon** [xerub/img4tool#2]
Thanks in advance.

make -C lzfse works fine.
However, make, command issues following error.
img4.c:14:10: fatal error: 'openssl/bn.h' file not found

**Comment by icylon** [comment]
After installing openssl (brew install openssl) and copying over the lib and other directory, I have a new error message.
ld: library not found for -lcrypto

**Comment by GeoSn0w** [comment]
install libcrypto.

**Comment by icylon** [comment]
Thanks,
On OS X Brew, libcrypto is not available.
I brew installed both libcryptopp and libgcrypt but same error.

**Comment by stek29** [comment]
> After installing openssl (brew install openssl) and copying over the lib and other directory

I hope you haven't copied libssl and include files to -L path

Just in case someone else gets here with the same error: Do not copy libssl, either force link OpenSSL or add cflags and ldflags as homebrew suggests

libcrypto is part of OpenSSL.

I doubt anyone can be that... special... like op, but I still think I have to leave this comment.

**Comment by rhcp011235** [comment]
To fix this: xcode-select --install

**Comment by stek29** [comment]
xcode-select install would install tools like make and clang 
You'll need to get openssl manually (via Homebrew for example)

**Comment by ghost** [comment]
img4.c:14:10: fatal error: 'openssl/bn.h' file not found
#include <openssl/bn.h> what to do

**Comment by stek29** [comment]
`brew install stek29/idevice/img4tool-xerub`

**Comment by xerub** [comment]
Closing as this project is retired. Please use https://github.com/xerub/img4lib/ instead.
